# This is a basic workflow to help you get started with Actions

name: BuildDocs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # [pull_request_target]
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions: 
      contents: write
      pull-requests: write
      pages: write
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
          
      # Runs a single command using the runners shell
      - name: Setup Ruby
        uses: ruby/setup-ruby@8575951200e472d5f2d95c625da0c7bec8217c42 # v1.161.0
        with:
          ruby-version: '3.1' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          cache-version: 0 # Increment this number if you need to re-download cached gems
      - name: install Gem
        run: gem install asciidoctor
      - name: create file
        run: asciidoctor -o ./src/modelldokumentation.html README.adoc
  

      #- name: Generate HTML
      #  run: |
      #    asciidoctor -o $GITHUB_WORKSPACE/output.html README.adoc 
      # Runs a single command using the runners shell
      #- name: asciidoctor-ghpages
      #  uses: manoelcampos/asciidoctor-ghpages-action@v2
      #  with:
      #    pdf_build: true
      #    asciidoctor_params: --attribute=nofooter
      - name: Move HTML to Repository
        run: |
          mv ./src/modelldokumentation.html ./src/generated/modelldokumentation.html
      
      - name: Commit HTML
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Action"
          git add generated/modelldokumentation.html
          git diff-index --quiet HEAD || git commit -m "Generate HTML from AsciiDoc" && git push